### PR TITLE
Update classes.py

### PR DESCRIPTION
**Pull request by StumpyFrostreaver**
Think there was a typo on the pdfmine -> pdfminer on line 22 :-)

### CODE REVIEW

**Comment by timClicks** [comment]
Awesome, thanks for this. Sorry about the problem!

**Comment by StumpyFrostreaver** [comment]
No worries at all! Thanks for the library!! :-)

Was looking at PDFMiner and wondering why it wasn't as simple as slate. So
was quite pleased to find it!!

**Comment by StumpyFrostreaver** [comment]
Thanks again!

I was wondering, is there a nice and easy way via Slate to handle/work with
tables?

Thanks,
Mark.

---
Mark Cline
<mark@clarmitage.ca>
mark@clarmitage.ca
Please consider the environment before printing this email.
Check out PeopleForGood.ca <http://peopleforgood.ca/>.

**Comment by StumpyFrostreaver** [comment]
Howdy Sir!

I was wondering if there was a way I could install version 0.5.1 of slate?
I can see I can use pip to get the latest from Git, but I was wondering if
I could specify the version, or if there is a tag or something I could use?

Do you know if that is possible?

Thanks,
Mark.

---
Mark Cline
<mark@clarmitage.ca>
mark@clarmitage.ca
Please consider the environment before printing this email.
Check out PeopleForGood.ca <http://peopleforgood.ca/>.

**Comment by StumpyFrostreaver** [comment]
I think I figured it out:
sudo pip3 install git+
https://github.com/timClicks/slate@5abf5542682627dd198fbb1c955c92187cec1dcb

although think it would make sense to tag the release?

Thanks,
Mark.

---
Mark Cline
<mark@clarmitage.ca>
mark@clarmitage.ca
Please consider the environment before printing this email.
Check out PeopleForGood.ca <http://peopleforgood.ca/>.

**Pull request merged**
